apiVersion: v1
kind: Pod
metadata:
  name: formal-nas-syncer
spec:
  containers:
  - name: syncer
    image: python:3.9-slim
    command: ["/bin/bash", "-c", "sleep infinity"]
    volumeMounts:
    - mountPath: /formal-nas
      name: work-volume
  volumes:
  - name: work-volume
    persistentVolumeClaim:
      claimName: formal-nas-pvc
